function loadData(name) {
    var paraElement = document.getElementById("para");
    if (name == "btn1") {
        paraElement.innerHTML = "<table border='2' style='width: 400px ;background-color:#8084b9';><tr><td >Boat type : Small <br> Duration : 1hr <br> Location : Balapitiya <br>&emsp;&emsp;&emsp;&emsp; Nuwara Eliya <br>&emsp;&emsp;&emsp;&emsp; Gampaha <br>&emsp;&emsp;&emsp;&emsp; Matara <br><br> <b>Price = Rs 2000.00 per person <b> <br><br></td></tr> <tr><td>Boat type : Medium <br> Duration : 2.00hr <br>Location : Balapitiya <br>&emsp;&emsp;&emsp;&emsp; Nuwara Eliya <br>&emsp;&emsp;&emsp;&emsp; Gampaha <br>&emsp;&emsp;&emsp;&emsp; Matara<br><br> <b>Price = Rs 2500.00 per person <b> <br><br></td></tr>  <tr><td>Boat type : Large <br> Duration : 3.00hr <br> Location : Balapitiya <br>&emsp;&emsp;&emsp;&emsp; Nuwara Eliya <br>&emsp;&emsp;&emsp;&emsp; Gampaha <br>&emsp;&emsp;&emsp;&emsp; Matara <br><br><b> Price = Rs 3000.00 per person </b></td></tr></table>";
      paraElement.classList.add("highlight");
    } else if (name == "btn2") {
        paraElement.innerHTML = "<table border='2' style='width: 400px;background-color:#6871e2';><tr><td>Boat type : Small <br> Duration : 1.15hr <br> Location : Balapitiya <br>&emsp;&emsp;&emsp;&emsp; Nuwara Eliya <br>&emsp;&emsp;&emsp;&emsp; Gampaha <br>&emsp;&emsp;&emsp;&emsp; Matara <br><br> <b>Price = Rs 2100.00 per person <b> <br><br></td></tr> <tr><td>Boat type : Medium <br> Duration : 2.15hr <br>Location : Balapitiya <br>&emsp;&emsp;&emsp;&emsp; Nuwara Eliya <br>&emsp;&emsp;&emsp;&emsp; Gampaha <br>&emsp;&emsp;&emsp;&emsp; Matara<br><br> <b>Price = Rs 2600.00 per person <b> <br><br></td></tr>  <tr><td>Boat type : Large <br> Duration : 3.15hr <br> Location : Balapitiya <br>&emsp;&emsp;&emsp;&emsp; Nuwara Eliya <br>&emsp;&emsp;&emsp;&emsp; Gampaha <br>&emsp;&emsp;&emsp;&emsp; Matara <br><br><b> Price = Rs 3100.00 per person </b></td></tr></table>";
      paraElement.classList.add("highlight");
    } else if (name == "btn3") {
        paraElement.innerHTML = "<table border='2' style='width: 400px;background-color:#0a84e3';><tr><td>Boat type : Small <br> Duration : 1.30hr <br> Location : Balapitiya <br>&emsp;&emsp;&emsp;&emsp; Nuwara Eliya <br>&emsp;&emsp;&emsp;&emsp; Gampaha <br>&emsp;&emsp;&emsp;&emsp; Matara <br><br> <b>Price = Rs 2200.00 per person <b> <br><br></td></tr> <tr><td>Boat type : Medium <br> Duration : 2.30hr <br>Location : Balapitiya <br>&emsp;&emsp;&emsp;&emsp; Nuwara Eliya <br>&emsp;&emsp;&emsp;&emsp; Gampaha <br>&emsp;&emsp;&emsp;&emsp; Matara<br><br> <b>Price = Rs 2700.00 per person <b> <br><br></td></tr>  <tr><td>Boat type : Large <br> Duration : 3.30hr <br> Location : Balapitiya <br>&emsp;&emsp;&emsp;&emsp; Nuwara Eliya <br>&emsp;&emsp;&emsp;&emsp; Gampaha <br>&emsp;&emsp;&emsp;&emsp; Matara <br><br><b> Price = Rs 3200.00 per person </b></td></tr></table>";
      paraElement.classList.add("highlight");
    } else if (name == "btn4") {
        paraElement.innerHTML = "<table border='2' style='width: 400px;background-color:#7db6e2';><tr><td>Boat type : Small <br> Duration : 1.45hr <br> Location : Balapitiya <br>&emsp;&emsp;&emsp;&emsp; Nuwara Eliya <br>&emsp;&emsp;&emsp;&emsp; Gampaha <br>&emsp;&emsp;&emsp;&emsp; Matara <br><br> <b>Price = Rs 2300.00 per person <b> <br><br></td></tr> <tr><td>Boat type : Medium <br> Duration : 2.45hr <br>Location : Balapitiya <br>&emsp;&emsp;&emsp;&emsp; Nuwara Eliya <br>&emsp;&emsp;&emsp;&emsp; Gampaha <br>&emsp;&emsp;&emsp;&emsp; Matara<br><br> <b>Price = Rs 2800.00 per person <b> <br><br></td></tr>  <tr><td>Boat type : Large <br> Duration : 3.45hr <br> Location : Balapitiya <br>&emsp;&emsp;&emsp;&emsp; Nuwara Eliya <br>&emsp;&emsp;&emsp;&emsp; Gampaha <br>&emsp;&emsp;&emsp;&emsp; Matara <br><br><b> Price = Rs 3300.00 per person </b></td></tr></table>";
      paraElement.classList.add("highlight");
    } else if (name == "btn5") {
        paraElement.innerHTML = "<table border='2' style='width: 400px;background-color:#bec1e6';><tr><td>Boat type : Small <br> Duration : 2hr <br> Location : Balapitiya <br>&emsp;&emsp;&emsp;&emsp; Nuwara Eliya <br>&emsp;&emsp;&emsp;&emsp; Gampaha <br>&emsp;&emsp;&emsp;&emsp; Matara <br><br> <b>Price = Rs 2400.00 per person <b> <br><br></td></tr> <tr><td>Boat type : Medium <br> Duration : 3.00hr <br>Location : Balapitiya <br>&emsp;&emsp;&emsp;&emsp; Nuwara Eliya <br>&emsp;&emsp;&emsp;&emsp; Gampaha <br>&emsp;&emsp;&emsp;&emsp; Matara<br><br> <b>Price = Rs 2900.00 per person <b> <br><br></td></tr>  <tr><td>Boat type : Large <br> Duration : 4.00hr <br> Location : Balapitiya <br>&emsp;&emsp;&emsp;&emsp; Nuwara Eliya <br>&emsp;&emsp;&emsp;&emsp; Gampaha <br>&emsp;&emsp;&emsp;&emsp; Matara <br><br><b> Price = Rs 3400.00 per person </b></td></tr></table>";
      paraElement.classList.add("highlight");
    } 
    
  }